<script src="http://localhost/Medicare/views/admin/assets/lib\jquery\jquery.min.js" type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\perfect-scrollbar\js\perfect-scrollbar.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/js/app.js" type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\jquery-ui\jquery-ui.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\select2\js\select2.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\select2\js\select2.full.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\bootstrap-slider\bootstrap-slider.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\datetimepicker\js\bootstrap-datetimepicker.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\datatables\datatables.net\js\jquery.dataTables.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\datatables\datatables.net-bs4\js\dataTables.bootstrap4.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\datatables\datatables.net-buttons\js\dataTables.buttons.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\datatables\datatables.net-buttons\js\buttons.flash.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\datatables\jszip\jszip.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\datatables\pdfmake\pdfmake.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\datatables\pdfmake\vfs_fonts.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\datatables\datatables.net-buttons\js\buttons.colVis.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\datatables\datatables.net-buttons\js\buttons.print.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\datatables\datatables.net-buttons\js\buttons.html5.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\datatables\datatables.net-buttons-bs4\js\buttons.bootstrap4.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\datatables\datatables.net-responsive\js\dataTables.responsive.min.js"
        type="text/javascript"></script>
<script src="http://localhost/Medicare/views/admin/assets/lib\datatables\datatables.net-responsive-bs4\js\responsive.bootstrap4.min.js"
        type="text/javascript"></script>